{% set name = "tad-multicharge" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tad_multicharge-{{ version }}.tar.gz
  sha256: 815655a7dc2e732e334703b4db87b306ca8394d11569ebc9797b36216bd48283

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools
    - pip
  run:
    - python >=3.8,<3.13
    - numpy <2
    - tad-mctc
    - pytorch >=1.11,<2.5

test:
  imports:
    - tad_multicharge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tad-mctc/tad-multicharge
  summary: Torch Autodiff Implementation of Charge Models
  dev_url: https://github.com/tad-mctc/tad-multicharge
  doc_url: https://tad-multicharge.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
