{% set name = "tad-multicharge" %}
{% set version = "0.3.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tad_multicharge-{{ version }}.tar.gz
  sha256: b54e065d222e82f510f73e3d15ca6fb9e40782acb1709b7e97daf2aa2f56a1cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2
    - pytorch >=1.11,<3
    - tad-mctc
    - typing-extensions

test:
  imports:
    - tad_multicharge
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tad-mctc/tad-multicharge
  summary: Torch Autodiff Implementation of Charge Models
  dev_url: https://github.com/tad-mctc/tad-multicharge
  doc_url: https://tad-multicharge.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
