{% set name = "tad-multicharge" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tad_multicharge-{{ version }}.tar.gz
  sha256: ef26d0ef7f59854ce6d64131bbd8d98744812d03298983ebfeb6940698d17516

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy
    - tad-mctc
    - pytorch >=1.11

test:
  imports:
    - tad_multicharge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tad-mctc/tad-multicharge
  summary: Torch Autodiff Implementation of Charge Models
  dev_url: https://github.com/tad-mctc/tad-multicharge
  doc_url: https://tad-multicharge.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
